In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [17]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)
print(np.show_config())


1.26.3
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.7",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/opt/arm64-builds/include",
      "lib directory": "/opt/arm64-builds/lib",
      "openblas configuration": "USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC

/Users/haddock_ana/anaconda3/envs/Ironhack/lib/python3.11/site-packages/numpy/__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [80]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.randint(100, size=(2, 3, 5))# (block, rows, columns)
print(a)

[[[30 12 53 92 61]
  [18 16 66 86 10]
  [91 61 49 38 19]]

 [[89 71 64 83 97]
  [94 61  4 61 44]
  [34 26  3 93 49]]]


In [47]:
a = np.random.randint (100, size=(5, 3,2 )) #transpose array to generate a 2x3x5 array
transposed_a = np.transpose(a)
transposed_a

array([[[53, 53, 93, 32,  9],
        [71, 57, 19, 53, 52],
        [32, 14, 69, 10, 49]],

       [[67,  3,  5, 35, 77],
        [45, 13, 49, 43, 94],
        [29, 73,  7, 42, 71]]])

In [45]:
list1 = np.random.randit (1,5)

array_new = np.array(([1, 2, 3, 4, 5], [2, 2, 0, 7, 5], [2, 2, 0, 7, 5]))
array_new

array([[1, 2, 3, 4, 5],
       [2, 2, 0, 7, 5],
       [2, 2, 0, 7, 5]])

In [68]:
list1 = np.random.randint(10, size=(1, 1, 5))
list2 = np.random.randint(10, size=(1, 1, 5))
list3 = np.random.randint(10, size=(1, 1, 5))

array_new = np.array ((list1, list2, list3))
array_new

array([[[[7, 5, 7, 5, 1]]],


       [[[7, 3, 9, 7, 4]]],


       [[[1, 2, 9, 8, 7]]]])

In [102]:
#4. Print a.

print (a)

[[[30 12 53 92 61]
  [18 16 66 86 10]
  [91 61 49 38 19]]

 [[89 71 64 83 97]
  [94 61  4 61 44]
  [34 26  3 93 49]]]


In [8]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [103]:
b = np.ones((5, 3, 2))

In [104]:
#6. Print b.
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [10]:
#7. Do a and b have the same size? How do you prove that in Python code?

In [105]:
if a.shape == b.shape:
    print("Arrays a and b have the same size.")
else:
    print("Arrays a and b do not have the same size.")

Arrays a and b do not have the same size.


In [106]:
#8. Are you able to add a and b? Why or why not?

if a.shape == b.shape:
    # Add arrays a and b element-wise
    result = a + b
    print("Arrays a and b can be added.")
else:
    print("Arrays a and b do not have the same size.")# And that is why they cannot be added to each other with a +

Arrays a and b do not have the same size.


In [12]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [107]:
c = np.transpose (b)
print (c)
print (c.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


In [167]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a + c
d


array([[[31., 13., 54., 93., 62.],
        [19., 17., 67., 87., 11.],
        [92., 62., 50., 39., 20.]],

       [[90., 72., 65., 84., 98.],
        [95., 62.,  5., 62., 45.],
        [35., 27.,  4., 94., 50.]]])

In [14]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [109]:
dif_arr = d - a
dif_arr # The difference between d and a is equal to the array c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [110]:
#12. Multiply a and c. Assign the result to e.
e = a * c
e

array([[[30., 12., 53., 92., 61.],
        [18., 16., 66., 86., 10.],
        [91., 61., 49., 38., 19.]],

       [[89., 71., 64., 83., 97.],
        [94., 61.,  4., 61., 44.],
        [34., 26.,  3., 93., 49.]]])

In [119]:

#13. Does e equal to a? Why or why not?
if np.array_equal(a, e):
    print("Arrays a and e are the same because e.array is a.array * value of c.array which equals 1.")
else:
    print("Arrays a and e are not the same.")

Arrays a and e are the same because e.array is a.array * value of c.array which equals 1.


In [150]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max (d)
d_min = np.min (d)
d_mean = np.mean (d)
print (f" The max number for Array 'd' is {d_max}, the mininum number is {d_min} and the mean is {d_mean}")

 The max number for Array 'd' is 75.0, the mininum number is 75.0 and the mean is 75.0


In [168]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty([2, 3, 5])

In [ ]:

#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [174]:

# Create an empty array f with the same shape as d
f = np.empty_like(d)

# Apply conditions to populate f
f[(d > d_min) & (d < d_mean)] = 25
f[d == d_mean] = 50
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_min] = 0
f[d == d_max] = 100

print("Array f:")
print(f)

Array f:
[[[ 25.  25.  75.  75.  75.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  75.  25.  25.  25.]]

 [[ 75.  75.  75.  75. 100.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  25.   0.  75.  25.]]]


In [ ]:

#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [176]:
print ("Array d:")
print (d)
print("Array f:")
print(f)

Array d:
[[[31. 13. 54. 93. 62.]
  [19. 17. 67. 87. 11.]
  [92. 62. 50. 39. 20.]]

 [[90. 72. 65. 84. 98.]
  [95. 62.  5. 62. 45.]
  [35. 27.  4. 94. 50.]]]
Array f:
[[[ 25.  25.  75.  75.  75.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  75.  25.  25.  25.]]

 [[ 75.  75.  75.  75. 100.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  25.   0.  75.  25.]]]


In [ ]:

#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.


In [184]:

def f_to_string(value): # Define a function to convert integers to strings
    if value == 0:
        return 'A'
    elif value == 25:
        return 'B'
    elif value == 50:
        return 'C'
    elif value == 75:
        return 'D'
    elif value == 100:
        return 'E'
    else:
        return 'null'

str_f = np.vectorize(map_to_string)(f) # we apply the function to each element of the array f with the np.vectorize

# Print the modified array
print(str_f)

[[['B' 'B' 'D' 'D' 'D']
  ['B' 'B' 'D' 'D' 'B']
  ['D' 'D' 'B' 'B' 'B']]

 [['D' 'D' 'D' 'D' 'E']
  ['D' 'D' 'B' 'D' 'B']
  ['B' 'B' 'A' 'D' 'B']]]
